apiVersion: batch/v1
kind: CronJob
metadata:
  name: cron-parking
spec:
  schedule: "00 05 * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: cron-parking
            image: lyabomyr/parking-tele-bot:latest
            command: ["python3"]
            args: ["cron.py"]
            imagePullPolicy: IfNotPresent
          restartPolicy: OnFailure