apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: base-chart
spec:
  releaseName: parking-tele-bot
  chart:
    spec:
      version: 0.3.1
    fullnameOverride: parking-tele-bot
    name: parking-tele-bot
    image:
      repository: parking-tele-bot
      tag: latest 
    extraArgs:
    - "/parking_bot/parking_tele_bot.py "
    resources:
      limits:
        cpu: 512m
        memory: 512Gi
      requests:
        cpu: 512m
        memory: 512Mi
    affinity:
      nodeAffinity:
        requiredDuringSchedulingIgnoredDuringExecution:
          nodeSelectorTerms:
          - matchExpressions:
            - key: application
              operator: In
              values:
              - mix
